### PR TITLE
chore(dependencies): Update Angular to v4.0.0 and update other dependencies accordingly

### PR DESCRIPTION
**Pull request by frederikprijck**
Updated `01-Login` sample to use the latest dependencies.

There's still a lot applications to migrate. But I guess it's a good idea to check if you guys agree with this PR before migrating the others. Btw, is this repo still to be used or should we use https://github.com/auth0-samples/auth0-angular-samples/ ? If so, I can move the PR (parts) to that repo.

Overview of my changes:

- used `angular-in-memory-web-api` instead of `angular2-in-memory-web-api` as the package has been renamed.
- Upgrade TypeScript to 2+.
- Removed `typings` and make use of `@types`. This required to edit the `tsconfig.json` file to include `lib` due to `@types/core-js`.
- Update Angular, rxjs, zonejs, ..

Note: I didn't upgrade `tslint` as part of this PR. If you prefer to upgrade `tslint` using this PR aswell, let me know!

### CODE REVIEW

**Comment by chenkie** [comment]
Thanks for this one @frederikprijck! 

The other samples repo you mentioned will be for a new version of the quickstarts to be released shortly. The two repos will be merged and branched.

Regarding your changes, they look good. I think we can roll with them for the rest.

**Comment by chenkie** [comment]
Just a heads up for the other samples, I removed this line from `package.json`:

```bash
"postinstall": "typings install",
```

It was failing on that script.

**Comment by frederikprijck** [comment]
Oops, my bad. 🙈 Thanks for fixing!

**Comment by chenkie** [comment]
np thanks!

**Pull request merged**
